/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.Edicao;

import br.com.satc.pessoa.Vendedor;
import br.com.satc.singleton.BancoVendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Edutec
 */
public class EdicaoVendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form EdicaoAnimal
     */
    public EdicaoVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jBProcurar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        JbCancelar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jTFEspecialidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFRg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFCargo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFSetor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFSalario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLTitulo.setText("Edição do Vendedor");

        jLabel1.setText("ID:");

        jBProcurar.setText("Procurar");
        jBProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcurarActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Editar");
        jBCadastrar.setEnabled(false);
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        JbCancelar.setText("Cancelar");
        JbCancelar.setEnabled(false);
        JbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCancelarActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jTFEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEspecialidadeActionPerformed(evt);
            }
        });

        jLabel8.setText("Especialidade:");

        jLabel4.setText("RG:");

        jLabel3.setText("CPF:");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jTFCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCargoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cargo:");

        jTFSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSetorActionPerformed(evt);
            }
        });

        jLabel6.setText("Setor:");

        jLabel5.setText("Salário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBProcurar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBCadastrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBSair)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFEspecialidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLTitulo)
                                .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jTFNome)
                                        .addComponent(jTFRg, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                        .addComponent(jTFCpf))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(70, 70, 70))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addComponent(jTFSalario)
                                        .addComponent(jTFSetor)
                                        .addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBProcurar)
                    .addComponent(jBCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCancelar)
                    .addComponent(jBSair))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcurarActionPerformed
        try{
            int id = Integer.parseInt(jTID.getText());
            jTFCargo.setText(BancoVendedor.getInstance().vendedores.get(id).getCargo());
            jTFRg.setText(BancoVendedor.getInstance().vendedores.get(id).getRg());
            jTFCpf.setText(BancoVendedor.getInstance().vendedores.get(id).getCpf());
            jTFSetor.setText(BancoVendedor.getInstance().vendedores.get(id).getSetor());
            jTFEspecialidade.setText(BancoVendedor.getInstance().vendedores.get(id).getEspecialidade());
            jTFSalario.setText(String.valueOf(BancoVendedor.getInstance().vendedores.get(id).getSalario()));
            jTFNome.setText(BancoVendedor.getInstance().vendedores.get(id).getNome());
            JbCancelar.setEnabled(true);
            jBProcurar.setEnabled(false);
            jBCadastrar.setEnabled(true);
            jTID.setEnabled(false);
            jTFCargo.setEnabled(true);
            jTFRg.setEnabled(true);
            jTFCpf.setEnabled(true);
            jTFSetor.setEnabled(true);
            jTID.setEnabled(false);
            jTFEspecialidade.setEnabled(true);
            jTFCargo.setEnabled(true);
            jTFSalario.setEnabled(true);
            jTFNome.setEnabled(true);
        }catch(IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(null, "Id inexistente");
        }
    }//GEN-LAST:event_jBProcurarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed

        String nome,rg,cpf,cargo,setor,especialidade, logradouro = null;
        double salario;
        float renda = 0;
        if (!(jTFRg.getText().equals("") || jTFCpf.getText().equals("") || jTFSetor.getText().equals("") || jTFSalario.getText().equals("")
            || jTFNome.getText().equals("") || jTFCargo.getText().equals("") || jTFEspecialidade.getText().equals(""))){

        cargo = jTFCargo.getText();
        rg = jTFRg.getText();
        cpf = jTFCpf.getText();
        setor = jTFSetor.getText();
        salario = Double.parseDouble(jTFSalario.getText());
        especialidade = jTFEspecialidade.getText();
        nome = jTFNome.getText();


       
            BancoVendedor.getInstance().vendedores.set(Integer.parseInt(jTID.getText()), new Vendedor(setor, cargo, salario, nome, rg, cpf, logradouro, renda,especialidade));
            JOptionPane.showMessageDialog(this, "Modificado com Sucesso");
            JbCancelar.setEnabled(false);
            jBProcurar.setEnabled(true);
            jBCadastrar.setEnabled(false);
            jTID.setEnabled(true);
            jTFCargo.setEnabled(false);
            jTFRg.setEnabled(false);
            jTFCpf.setEnabled(false);
            jTFSetor.setEnabled(false);
            jTID.setEnabled(true);
            jTFEspecialidade.setEnabled(false);
            jTFCargo.setEnabled(false);
            jTFSalario.setEnabled(false);
            jTFNome.setEnabled(false);
            jTFNome.setText("");
            jTID.setText("");
            jTFRg.setText("");
            jTFCpf.setText("");
            jTFCargo.setText("");
            jTFSalario.setText("");
            jTFEspecialidade.setText("");
            jTFSetor.setText("");
        
    }//GEN-LAST:event_jBCadastrarActionPerformed
    }
    private void JbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCancelarActionPerformed
        JbCancelar.setEnabled(false);
        jBProcurar.setEnabled(true);
        jBCadastrar.setEnabled(false);
            jTID.setEnabled(true);
            jTFCargo.setEnabled(false);
            jTFRg.setEnabled(false);
            jTFCpf.setEnabled(false);
            jTFSetor.setEnabled(false);
            jTID.setEnabled(true);
            jTFEspecialidade.setEnabled(false);
            jTFCargo.setEnabled(false);
            jTFSalario.setEnabled(false);
            jTFNome.setEnabled(false);
            jTFNome.setText("");
            jTID.setText("");
            jTFRg.setText("");
            jTFCpf.setText("");
            jTFCargo.setText("");
            jTFSalario.setText("");
            jTFEspecialidade.setText("");
            jTFSetor.setText("");
    }//GEN-LAST:event_JbCancelarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jTFEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEspecialidadeActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jTFCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCargoActionPerformed

    private void jTFSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSetorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCancelar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBProcurar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTFCargo;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFEspecialidade;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFRg;
    private javax.swing.JTextField jTFSalario;
    private javax.swing.JTextField jTFSetor;
    private javax.swing.JTextField jTID;
    // End of variables declaration//GEN-END:variables
}
