/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.grafico;

import br.com.satc.pessoa.Funcionario;
import br.com.satc.pessoa.Vendedor;
import br.com.satc.singleton.BancoVendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Edutec
 */
public class CadastroV extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroV
     */
    public CadastroV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblCadastroVendedor = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLblCPF = new javax.swing.JLabel();
        jTxtCPF = new javax.swing.JTextField();
        jTxtCargo = new javax.swing.JTextField();
        jLblCargo = new javax.swing.JLabel();
        jTxtRG = new javax.swing.JTextField();
        jLblRG = new javax.swing.JLabel();
        jTxtComissao = new javax.swing.JTextField();
        jLblComissao = new javax.swing.JLabel();
        jTxtSetor = new javax.swing.JTextField();
        jLblSetor = new javax.swing.JLabel();
        jTxtSalario = new javax.swing.JTextField();
        jLblSalario = new javax.swing.JLabel();
        jLblEspecialidade = new javax.swing.JLabel();
        jTxtEspecialidade = new javax.swing.JTextField();
        jBtnCadastrar = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();

        setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLblCadastroVendedor.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLblCadastroVendedor.setText("Cadastro Vendedor");

        jLblNome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLblNome.setText("Nome:");

        jLblCPF.setText("CPF:");

        jLblCargo.setText("Cargo:");

        jLblRG.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLblRG.setText("RG:");

        jLblComissao.setText("Comissão:");

        jLblSetor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLblSetor.setText("Setor:");

        jLblSalario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLblSalario.setText("Salário:");

        jLblEspecialidade.setText("Especialidade:");

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });

        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblRG)
                        .addComponent(jTxtRG)
                        .addComponent(jLblCargo)
                        .addComponent(jTxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblNome)
                        .addComponent(jTxtNome)
                        .addComponent(jLblCPF)
                        .addComponent(jTxtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLblSetor)
                        .addComponent(jTxtSetor)
                        .addComponent(jLblComissao)
                        .addComponent(jTxtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblSalario)
                    .addComponent(jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEspecialidade)
                    .addComponent(jTxtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLblCadastroVendedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jBtnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCadastroVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblComissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCadastrar)
                    .addComponent(jBtnSair))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        String nome,cargo = null,especialidade = null,setor = null,rg,cpf;
        Funcionario supervisor = null;
        float comissao,salario;
        
        if (!(jTxtNome.getText().equals("") || jTxtCPF.getText().equals("") || jTxtRG.getText().equals("") || jTxtCargo.getText().equals("") || jTxtEspecialidade.getText().equals("") || jTxtSetor.getText().equals("") || jTxtComissao.getText().equals("") || jTxtSalario.getText().equals(""))) {

            nome = jTxtNome.getText();
            cpf = jTxtCPF.getText();
            rg = jTxtRG.getText();
            
            try {
                comissao = Float.parseFloat(jTxtComissao.getText());
                salario = Float.parseFloat(jTxtSalario.getText());
                BancoVendedor.getInstance().vendedores.add(new Vendedor(nome, cargo, setor, rg, cpf, comissao, salario, especialidade, supervisor));
                JOptionPane.showMessageDialog(this, "Cadastro feito.");
                jTxtNome.setText("");
                jTxtCPF.setText("");
                jTxtRG.setText("");
                jTxtComissao.setText("");
                jTxtSalario.setText("");
                jTxtCargo.setText("");
                jTxtEspecialidade.setText("");
                jTxtSetor.setText("");
                
                
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(this, "Não deixe o(s) campos em branco.");
            }
        }
            
        
        
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblCadastroVendedor;
    private javax.swing.JLabel jLblCargo;
    private javax.swing.JLabel jLblComissao;
    private javax.swing.JLabel jLblEspecialidade;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRG;
    private javax.swing.JLabel jLblSalario;
    private javax.swing.JLabel jLblSetor;
    private javax.swing.JTextField jTxtCPF;
    private javax.swing.JTextField jTxtCargo;
    private javax.swing.JTextField jTxtComissao;
    private javax.swing.JTextField jTxtEspecialidade;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtRG;
    private javax.swing.JTextField jTxtSalario;
    private javax.swing.JTextField jTxtSetor;
    // End of variables declaration//GEN-END:variables
}
