/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.grafico;

/**
 *
 * @author Edutec
 */
public class ConsultaVend extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaVend
     */
    public ConsultaVend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBSair7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jRBCodigo = new javax.swing.JRadioButton();
        jLPesquisa = new javax.swing.JLabel();
        jRBNome = new javax.swing.JRadioButton();
        jTFCampoPesquisa = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();

        jBSair7.setText("Sair");
        jBSair7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSair7ActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        jRBCodigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRBCodigo.setText("Código");
        jRBCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCodigoActionPerformed(evt);
            }
        });

        jLPesquisa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLPesquisa.setText("Pesquisa");

        jRBNome.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRBNome.setSelected(true);
        jRBNome.setText("Nome");
        jRBNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBNomeActionPerformed(evt);
            }
        });

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFCampoPesquisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBPesquisar)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBNome)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))
                                .addComponent(jRBCodigo)
                                .addGap(55, 55, 55))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jBSair7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLPesquisa)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBNome)
                    .addComponent(jRBCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSair7)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSair7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSair7ActionPerformed
        dispose();
    }//GEN-LAST:event_jBSair7ActionPerformed

    private void jRBCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCodigoActionPerformed
        jRBNome.setSelected(false);
        jTFCampoPesquisa.setText("");
    }//GEN-LAST:event_jRBCodigoActionPerformed

    private void jRBNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBNomeActionPerformed
        jRBCodigo.setSelected(false);
        jTFCampoPesquisa.setText("");
    }//GEN-LAST:event_jRBNomeActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        List<ANIMAL> alist = new ArrayList();
        AnimalTableModel atm = new AnimalTableModel(alist);
        if (jRBNome.isSelected()){
            if(jCBAtivo.isSelected() && jCBInativo.isSelected()){
                atm = new AnimalTableModel(BancoAnimal.getInstance().pesquisaNome(
                    jTFCampoPesquisa.getText(), BancoAnimal.getInstance().animais));
        }else if(jCBAtivo.isSelected() && !jCBInativo.isSelected()){
            atm = new AnimalTableModel(BancoAnimal.getInstance().pesquisaNomeStatus(
                jTFCampoPesquisa.getText(), BancoAnimal.getInstance().animais, 'A'));
        }else if(!jCBAtivo.isSelected() && jCBInativo.isSelected()){
            atm = new AnimalTableModel(BancoAnimal.getInstance().pesquisaNomeStatus(
                jTFCampoPesquisa.getText(), BancoAnimal.getInstance().animais, 'I'));
        }
        }if (jRBCodigo.isSelected()){
            atm = new AnimalTableModel(BancoAnimal.getInstance().pesquisaCodigo(
                Integer.parseInt(jTFCampoPesquisa.getText()), BancoAnimal.getInstance().animais));
        }jTabela.setModel(atm);
    }//GEN-LAST:event_jBPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jBSair1;
    private javax.swing.JButton jBSair2;
    private javax.swing.JButton jBSair3;
    private javax.swing.JButton jBSair4;
    private javax.swing.JButton jBSair5;
    private javax.swing.JButton jBSair6;
    private javax.swing.JButton jBSair7;
    private javax.swing.JLabel jLPesquisa;
    private javax.swing.JRadioButton jRBCodigo;
    private javax.swing.JRadioButton jRBNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCampoPesquisa;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
