/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.grafico;

import br.com.satc.singleton.BancoVendedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Edutec
 */
public class EdicaoVendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form EdicaoVendedor
     */
    public EdicaoVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNome = new javax.swing.JLabel();
        jLSalario = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTEspecialidade = new javax.swing.JTextField();
        jLRG = new javax.swing.JLabel();
        jLEspecialidade = new javax.swing.JLabel();
        jTRG = new javax.swing.JTextField();
        jBEditar = new javax.swing.JButton();
        jTCPF = new javax.swing.JTextField();
        jBSair = new javax.swing.JButton();
        jLCPF = new javax.swing.JLabel();
        jLSetor = new javax.swing.JLabel();
        jTSetor = new javax.swing.JTextField();
        jTCargo = new javax.swing.JTextField();
        jLCargo = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jTSalario = new javax.swing.JTextField();
        jTComissao = new javax.swing.JTextField();
        jLComissao = new javax.swing.JLabel();
        jBProcurar = new javax.swing.JButton();
        jTID = new javax.swing.JTextField();
        jLID = new javax.swing.JLabel();

        jLNome.setText("Nome :");

        jLSalario.setText("Salário :");

        jLRG.setText("RG :");

        jLEspecialidade.setText("Especialidade :");

        jBEditar.setText("Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jLCPF.setText("CPF :");

        jLSetor.setText("Setor :");

        jLCargo.setText("Cargo :");

        jLTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLTitulo.setText("Edição de Vendedor");

        jLComissao.setText("Comissão :");

        jBProcurar.setText("Procurar");
        jBProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProcurarActionPerformed(evt);
            }
        });

        jLID.setText("ID do Vendedor :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLRG)
                            .addComponent(jLCPF)
                            .addComponent(jLSetor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(jTCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTSetor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTNome, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTSalario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(jTEspecialidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLCargo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLSalario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLEspecialidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLComissao, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTComissao, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jTCargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLID)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBProcurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLEspecialidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLComissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditar)
                    .addComponent(jBSair))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        String nome,rg,cpf,setor,cargo,especialidade;
        float salario,comissao;

        if (!(jTNome.getText().equals("") || jTRG.getText().equals("")
            || jTCPF.getText().equals("") || jTSetor.getText().equals("")
            || jTCargo.getText().equals("") || jTComissao.getText().equals("")
            || jTEspecialidade.getText().equals("") || jTSalario.getText().equals(""))){

        nome = jTNome.getText();
        rg = jTRG.getText();
        cpf = jTCPF.getText();
        setor = jTSetor.getText();
        cargo = jTCargo.getText();
        especialidade= jTEspecialidade.getText();
        try{
            salario = Float.parseFloat(jTSalario.getText());
            comissao = Float.parseFloat(jTComissao.getText());
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setNome(nome);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setRg(rg);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setCpf(cpf);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setSetor(setor);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setCargo(cargo);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setEspecialidade(especialidade);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setSalario(salario);
            BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).setComissao(comissao);
            JOptionPane.showMessageDialog(this, "Êxito na Edição.");
            jTCPF.setText("");
            jTCargo.setText("");
            jTEspecialidade.setText("");
            jTNome.setText("");
            jTRG.setText("");
            jTSalario.setText("");
            jTSetor.setText("");
            jTComissao.setText("");
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Salário ou Comissão inválidos : \n"+nfe);
        }
        }else{
            JOptionPane.showMessageDialog(this,"Campos em Branco.");

        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jBProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProcurarActionPerformed
     if (jTID.getText().equals("")){
     JOptionPane.showMessageDialog(this,"Campo em branco.");
     }else{
    try{
    jTNome.setText(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getNome());
    jTRG.setText(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getRg());
    jTCPF.setText(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getCpf());
    jTSetor.setText(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getSetor());
    jTCargo.setText(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getCargo());
    jTSalario.setText(Float.toString(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getSalario()));
    jTEspecialidade.setText(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getEspecialidade());
    jTComissao.setText(Float.toString(BancoVendedor.getInstance().vendedores.get(Integer.parseInt(jTID.getText())).getComissao()));
    }catch(IndexOutOfBoundsException ioobe){
         JOptionPane.showMessageDialog(this, "Vendedor inexistente.");
     }
     }
    }//GEN-LAST:event_jBProcurarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBProcurar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLComissao;
    private javax.swing.JLabel jLEspecialidade;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLRG;
    private javax.swing.JLabel jLSalario;
    private javax.swing.JLabel jLSetor;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTCargo;
    private javax.swing.JTextField jTComissao;
    private javax.swing.JTextField jTEspecialidade;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTNome;
    private javax.swing.JTextField jTRG;
    private javax.swing.JTextField jTSalario;
    private javax.swing.JTextField jTSetor;
    // End of variables declaration//GEN-END:variables
}
