/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.grafico;

import br.com.satc.singleton.Classe_Singleton;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Edicao_Vendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Edicao_Vendedor
     */
    public Edicao_Vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblComissao = new javax.swing.JLabel();
        jtxtCPF = new javax.swing.JTextField();
        jbtnProcurar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jtxtID = new javax.swing.JTextField();
        jlblCPF = new javax.swing.JLabel();
        jlblID = new javax.swing.JLabel();
        jlblNome = new javax.swing.JLabel();
        jlblSetor = new javax.swing.JLabel();
        jlblSalario = new javax.swing.JLabel();
        jtxtSetor = new javax.swing.JTextField();
        jtxtNome = new javax.swing.JTextField();
        jtxtCargo = new javax.swing.JTextField();
        jtxtEspecialidade = new javax.swing.JTextField();
        jlblCargo = new javax.swing.JLabel();
        jlblRG = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jlblEspeci = new javax.swing.JLabel();
        jtxtSalario = new javax.swing.JTextField();
        jtxtRG = new javax.swing.JTextField();
        jtxtComissao = new javax.swing.JTextField();
        jbtnEditar = new javax.swing.JButton();
        jlblID1 = new javax.swing.JLabel();
        jtxtIDSupervisor = new javax.swing.JTextField();
        jbtnProcurar1 = new javax.swing.JButton();
        jlblID2 = new javax.swing.JLabel();
        jtxtNomeSupervisor = new javax.swing.JTextField();

        jlblComissao.setText("Comissão :");

        jbtnProcurar.setText("Procurar");
        jbtnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcurarActionPerformed(evt);
            }
        });

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        jlblCPF.setText("CPF :");

        jlblID.setText("ID do Vendedor :");

        jlblNome.setText("Nome :");

        jlblSetor.setText("Setor :");

        jlblSalario.setText("Salário :");

        jtxtSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSetorActionPerformed(evt);
            }
        });

        jlblCargo.setText("Cargo :");

        jlblRG.setText("RG :");

        jlblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jlblTitulo.setText("Edição de Vendedor");

        jlblEspeci.setText("Especialidade :");

        jbtnEditar.setText("Editar");
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jlblID1.setText("ID do Supervisor:");

        jbtnProcurar1.setText("Procurar");
        jbtnProcurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcurar1ActionPerformed(evt);
            }
        });

        jlblID2.setText("Nome do Supervisor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtxtSetor)
                                .addComponent(jlblCargo)
                                .addComponent(jlblSalario)
                                .addComponent(jtxtSalario)
                                .addComponent(jlblEspeci)
                                .addComponent(jtxtEspecialidade)
                                .addComponent(jlblComissao)
                                .addComponent(jtxtComissao)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                    .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlblCPF)
                            .addComponent(jtxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblSetor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblRG, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtRG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblID)
                                .addGap(28, 28, 28)
                                .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlblID1)
                                        .addGap(26, 26, 26))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblID2)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtNomeSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(jtxtIDSupervisor))
                                .addGap(18, 18, 18)
                                .addComponent(jbtnProcurar1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jlblNome)
                    .addComponent(jlblTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jlblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblID)
                    .addComponent(jtxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblRG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblID1)
                        .addComponent(jtxtIDSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnProcurar1))
                    .addComponent(jlblCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblID2)
                    .addComponent(jtxtNomeSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblSetor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblEspeci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblComissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEditar)
                    .addComponent(jbtnSair))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcurarActionPerformed
        if (jtxtID.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Campo em branco.");
        }else{
            try{
                jtxtNome.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getNome());
                
                jtxtRG.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getRg());
                
                jtxtCPF.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getCpf());
                
                jtxtSetor.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getSetor());
                
                jtxtCargo.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getCargo());
                
                jtxtSalario.setText(Float.toString(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getSalario()));
                
                jtxtEspecialidade.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getEspecialidade());
                
                jtxtComissao.setText(Float.toString(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).getComissao()));
                
               
                
            }catch(IndexOutOfBoundsException ioobe){
                JOptionPane.showMessageDialog(this, "Vendedor inexistente.");
            }
        }
    }//GEN-LAST:event_jbtnProcurarActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        String nome, rg, cpf, cargo, supervisor, setor, especialidade;
        float salario,comissao;

        if (!(jtxtNome.getText().equals("") || jtxtRG.getText().equals("")
            || jtxtCPF.getText().equals("") || jtxtSetor.getText().equals("")
            || jtxtCargo.getText().equals("") || jtxtComissao.getText().equals("")
            || jtxtEspecialidade.getText().equals("") || jtxtSalario.getText().equals(""))){

        nome = jtxtNome.getText();
        rg = jtxtRG.getText();
        cpf = jtxtCPF.getText();
        setor = jtxtSetor.getText();
        cargo = jtxtCargo.getText();
        especialidade= jtxtEspecialidade.getText();
        try{
            salario = Float.parseFloat(jtxtSalario.getText());
            comissao = Float.parseFloat(jtxtComissao.getText());
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setNome(nome);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setRg(rg);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setCpf(cpf);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setSetor(setor);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setCargo(cargo);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setEspecialidade(especialidade);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setSalario(salario);
            Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtID.getText())).setComissao(comissao);
            JOptionPane.showMessageDialog(this, "Êxito na Edição.");
            jtxtCPF.setText("");
            jtxtCargo.setText("");
            jtxtEspecialidade.setText("");
            jtxtNome.setText("");
            jtxtRG.setText("");
            jtxtSalario.setText("");
            jtxtSetor.setText("");
            jtxtComissao.setText("");
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this,"Salário ou Comissão inválidos : \n"+nfe);
        }
        }else{
            JOptionPane.showMessageDialog(this,"Campos em Branco.");

        }
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtxtSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSetorActionPerformed

    private void jbtnProcurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcurar1ActionPerformed
         jtxtNomeSupervisor.setText(Classe_Singleton.getInstance().vendedores.get(Integer.parseInt(jtxtIDSupervisor.getText())).getNome());
    }//GEN-LAST:event_jbtnProcurar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnProcurar;
    private javax.swing.JButton jbtnProcurar1;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JLabel jlblCPF;
    private javax.swing.JLabel jlblCargo;
    private javax.swing.JLabel jlblComissao;
    private javax.swing.JLabel jlblEspeci;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblID1;
    private javax.swing.JLabel jlblID2;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblRG;
    private javax.swing.JLabel jlblSalario;
    private javax.swing.JLabel jlblSetor;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtxtCPF;
    private javax.swing.JTextField jtxtCargo;
    private javax.swing.JTextField jtxtComissao;
    private javax.swing.JTextField jtxtEspecialidade;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtIDSupervisor;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtNomeSupervisor;
    private javax.swing.JTextField jtxtRG;
    private javax.swing.JTextField jtxtSalario;
    private javax.swing.JTextField jtxtSetor;
    // End of variables declaration//GEN-END:variables
}
