/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.satc.grafico;
/**
 *
 * @author Edutec
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jQuadroInterno = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMCadastro = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenuItem();
        jMEdicao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jQuadroInterno.setVisible(true);

        javax.swing.GroupLayout jQuadroInternoLayout = new javax.swing.GroupLayout(jQuadroInterno.getContentPane());
        jQuadroInterno.getContentPane().setLayout(jQuadroInternoLayout);
        jQuadroInternoLayout.setHorizontalGroup(
            jQuadroInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jQuadroInternoLayout.setVerticalGroup(
            jQuadroInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        jMenu1.setText("Vendedor");

        jMCadastro.setText("Cadastro");
        jMCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastroActionPerformed(evt);
            }
        });
        jMenu1.add(jMCadastro);

        jMConsulta.setText("Consulta");
        jMConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(jMConsulta);

        jMEdicao.setText("Edição");
        jMEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEdicaoActionPerformed(evt);
            }
        });
        jMenu1.add(jMEdicao);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jQuadroInterno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jQuadroInterno)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastroActionPerformed
        // TODO add your handling code here:
        ConsultaVend novoCadastro = new ConsultaVend();
        jQuadroInterno.add(novoCadastro);
        novoCadastro.setVisible(true);
    }//GEN-LAST:event_jMCadastroActionPerformed

    private void jMConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaActionPerformed
        // TODO add your handling code here:
        ConsultaVend novoCadastro = new ConsultaVend();
        jQuadroInterno.add(novoCadastro);
        novoCadastro.setVisible(true);
    }//GEN-LAST:event_jMConsultaActionPerformed

    private void jMEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEdicaoActionPerformed
        // TODO add your handling code here:
        EdicaoVend novoCadastro = new EdicaoVend();
        jQuadroInterno.add(novoCadastro);
        novoCadastro.setVisible(true);
    }//GEN-LAST:event_jMEdicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMCadastro;
    private javax.swing.JMenuItem jMConsulta;
    private javax.swing.JMenuItem jMEdicao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JInternalFrame jQuadroInterno;
    // End of variables declaration//GEN-END:variables
}
